before_install:
  - if [ ! -d "$HOME/protobuf/lib" ]; then
  -  wget https://github.com/google/protobuf/archive/v3.5.1.tar.gz
  -  tar -xzvf v3.5.1.tar.gz
  -  cd v3.5.1 && ./configure --prefix=$HOME/protobuf && make && make install
  - else
  -   echo "Using cached directory."
  - fi

install: gradle wrapper

language: java

jdk:
- oraclejdk8
- openjdk8
